spring:
  application:
    name: patient-profile-service

  datasource:
    url: jdbc:postgresql://patient-profile-db:5432/patient-profile-db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect